const data = [
  {
    qestion: "Why We Use &lt;br&gt; Element",
    answer01: "To Make Text Bold",
    answer02: "To Make Text Italic",
    answer03: "To Add Breakline",
    answer04: "To Create Horizontal Line",
    right_answer: "To Add Breakline",
  },
  {
    qestion: "Is &lt;img&gt; Element Has Attribute href",
    answer01: "Yes",
    answer02: "No Its For Anchor Tag &lt;a&gt;",
    answer03: "All Elements Has This Attribute",
    answer04: "Answer 1 And 3 Is Right",
    right_answer: "No Its For Anchor Tag &lt;a&gt;",
  },
  {
    qestion: "How Can We Make Element Text Bold",
    answer01: "Putting It Inside &lt;b&gt; Tag",
    answer02: "Putting It Inside &lt;strong&gt; Tag",
    answer03: "Customizing It With Font-Weight Property In CSS",
    answer04: "All Answers Is Right",
    right_answer: "All Answers Is Right",
  },
  {
    qestion: "How Can We Include External Page Inside Our HTML Page",
    answer01: "By Using Include in HTML",
    answer02: "By Using Load In HTML",
    answer03: "By Using iFrame Tag",
    answer04: "All Solutions Is Wrong",
    right_answer: "By Using iFrame Tag",
  },
  {
    qestion: "CSS stands for..",
    answer01: "Cascade style sheets",
    answer02: "Color and style sheets",
    answer03: "Cascading style sheets",
    answer04: "None of the above",
    right_answer: "Cascading style sheets",
  },
  {
    qestion:
      "The property in CSS used to change the bacground color of an element is?",
    answer01: "bgcolor",
    answer02: "color",
    answer03: "background-color",
    answer04: "All of the above",
    right_answer: "background-color",
  },
  {
    qestion: "The CSS property used to control the element's font-size is..",
    answer01: "text-style",
    answer02: "text-size",
    answer03: "font-size",
    answer04: "None of the above",
    right_answer: "font-size",
  },
  {
    qestion: "The HTML attribute used to define the inline styles is..",
    answer01: "style",
    answer02: "styles",
    answer03: "class",
    answer04: "None of the above",
    right_answer: "style",
  },
  {
    qestion: "Which type of JavaScript language is?",
    answer01: "Object-Oriented",
    answer02: "Object-Based",
    answer03: "Assembly-language",
    answer04: "High-level",
    right_answer: "Object-Oriented",
  },
  {
    qestion: "What is the original name of  JavaScript?",
    answer01: "LiveScript",
    answer02: "Escript",
    answer03: "Mocha",
    answer04: "JavaScript",
    right_answer: "Mocha",
  },
  {
    qestion: "JavaScript code can be written in...",
    answer01: "JavaScript file (.js file)",
    answer02: "HTML document directly",
    answer03: "JavaScript file and in HTML document directly",
    answer04: "In style sheets (.css file)",
    right_answer: "JavaScript file and in HTML document directly",
  },
  {
    qestion: "Which symbol used separate JavaScript statements?",
    answer01: "Comma (,)",
    answer02: "Colon (:)",
    answer03: "Hyphen (_)",
    answer04: "Semicolon (;)",
    right_answer: "Semicolon (;)",
  },
];
